# Generated by Django 2.2 on 2021-06-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pin_code',
            new_name='distrito',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='provincia',
        ),
    ]
