# Generated by Django 2.2 on 2021-06-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210620_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='direccion',
        ),
        migrations.AlterField(
            model_name='order',
            name='distrito',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
