# Generated by Django 2.2 on 2021-06-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210620_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Empaquetado', 'Empaquetado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=10),
        ),
    ]
